### ISSUE TITLE
Action name is not title cased

### ISSUE THREAD

**Issue by Nigelw** [CharlesButcher/LaunchBar-smart-title-case#1]
It's a little ironic that the name of the action itself is sentence cased instead of title cased. I renamed my copy to "Convert to Smart Title Case". Submitting this issue to consider changing the name here :)

**Comment by CharlesButcher** [comment]
Nice try, but no cigar. I created this because I hate title case with a passion, and so am unwilling to memorise its stupid rules. You can rename it as you wish, but I'm not going to use title case anywhere I'm not paid to do so.
